
DEFAULT_CARD_NUMBER_VALIDATOR = "Luhn"


class ConfigKeyConstants:
    MASK_CHARACTER_KEY_NAME = "MASK_CHARACTER"
    MASK_UNMASKED_DIGITS_COUNT_KEY_NAME = "MASK_UNMASKED_DIGITS_COUNT"
    VALIDATION_METHOD = "CARD_NUMBER_VALIDATION_ALGORITHM"
